import Foundation
import PromiseKit
import Shared
#if !targetEnvironment(macCatalyst)
import CoreNFC
#endif

class TagActivityManager: TagManager {
    var isNFCAvailable: Bool {
        false
    }

    func readNFC() -> Promise<String> {
        .init(error: TagManagerError.nfcUnavailable)
    }

    func writeNFC(value: String) -> Promise<String> {
        .init(error: TagManagerError.nfcUnavailable)
    }

    func handle(userActivity: NSUserActivity) -> TagManagerHandleResult {
        guard let url = userActivity.webpageURL else {
            return .unhandled
        }

        let components = URLComponents(url: url, resolvingAgainstBaseURL: false)

        if let tag = Self.identifier(from: url) {
            let type = handledType(from: userActivity)
            if AllowedTag.contains(tag) {
                fireEvent(tag: tag).cauterize()
                return .handled(type)
            } else {
                return .requiresApproval(tag: tag, type: type)
            }
        }

        if let urlString = components?.queryItems?.first(where: { $0.name.lowercased() == "url" })?.value,
           let url = URL(string: urlString) {
            return .open(url)
        }

        return .unhandled
    }

    func handledType(from userActivity: NSUserActivity) -> TagManagerHandleResult.HandledType {
        .generic
    }

    static func url(for identifier: String) -> URL? {
        guard isValidTagIdentifier(identifier) else { return nil }

        var components = URLComponents()
        components.scheme = "https"
        components.host = "aiot.woowtech.io"
        components.path = "/tag/" + identifier
        return components.url
    }

    static func identifier(from url: URL) -> String? {
        guard let components = URLComponents(url: url, resolvingAgainstBaseURL: false),
              components.scheme?.lowercased() == "https",
              components.user == nil,
              components.password == nil,
              components.port == nil,
              components.query == nil,
              components.fragment == nil,
              isSupportedTagHost(components.host?.lowercased()) else {
            return nil
        }

        let encodedParts = components.percentEncodedPath.split(separator: "/", omittingEmptySubsequences: false)
        guard encodedParts.count == 3,
              encodedParts[0].isEmpty,
              encodedParts[1] == "tag",
              let identifier = String(encodedParts[2]).removingPercentEncoding,
              isValidTagIdentifier(identifier) else {
            return nil
        }
        return identifier
    }

    private static func isValidTagIdentifier(_ identifier: String) -> Bool {
        !identifier.isEmpty
            && identifier != "."
            && identifier != ".."
            && !identifier.contains("/")
            && !identifier.contains("?")
            && !identifier.contains("#")
    }

    private static func isSupportedTagHost(_ host: String?) -> Bool {
        guard let host else { return false }

        var hosts = ["aiot.woowtech.io", "www.home-assistant.io"]
        if Current.appConfiguration == .debug {
            hosts.append("next.home-assistant.io")
        }
        return hosts.contains(host)
    }
}

#if !targetEnvironment(macCatalyst)
class iOSTagManager: TagActivityManager {
    override var isNFCAvailable: Bool {
        NFCNDEFReaderSession.readingAvailable
    }

    override func readNFC() -> Promise<String> {
        let reader = NFCReader()
        var readerRetain: NFCReader? = reader

        return firstly {
            reader.promise
        }.ensure {
            withExtendedLifetime(readerRetain) {
                readerRetain = nil
            }
        }.then {
            Self.identifier(from: $0)
        }
    }

    override func writeNFC(value: String) -> Promise<String> {
        guard let tagURL = Self.url(for: value),
              let uriPayload = NFCNDEFPayload.wellKnownTypeURIPayload(url: tagURL),
              let aarPayload = NFCNDEFPayload.androidPackage(payload: "com.woowtech.aiot") else {
            return .init(error: TagManagerError.notHomeAssistantTag)
        }

        let writer = NFCWriter(requiredPayload: [uriPayload], optionalPayload: [aarPayload])
        var writerRetain: NFCWriter? = writer

        return firstly {
            writer.promise
        }.ensure {
            withExtendedLifetime(writerRetain) {
                writerRetain = nil
            }
        }.then { message in
            // we use the same logic as reading, so we can be sure the identifier is right
            Self.identifier(from: message)
        }
    }

    override func handledType(from userActivity: NSUserActivity) -> TagManagerHandleResult.HandledType {
        let ndefRecord = userActivity.ndefMessagePayload.records.first
        if ndefRecord == nil || ndefRecord?.typeNameFormat == .empty {
            /*
             For user activities not generated by background tag reading, ndefMessagePayload returns a message
             that contains only one NFCNDEFPayload record. That record has a typeNameFormat of NFCTypeNameFormat
             */
            return .generic
        } else {
            return .nfc
        }
    }

    private static func identifier(from message: NFCNDEFMessage) -> Promise<String> {
        firstly {
            .value(message.records)
        }.compactMapValues { payload in
            payload.wellKnownTypeURIPayload()
        }.compactMapValues { url -> String? in
            Self.identifier(from: url)
        }.map {
            if let value = $0.first {
                return value
            } else {
                throw TagManagerError.notHomeAssistantTag
            }
        }
    }
}
#endif
